config/routes.rb
ShishaApp::Application.routes.draw do
  resources :shishas

end

app/models/shisha.rb
class Shisha < ActiveRecord::Base
validates_presence_of :name
validates_presence_of :address
validates_presence_of :latitude
validates_presence_of :longitude
validates_presence_of :isDetailed
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/shishas_controller.rb
class ShishasController < ApplicationController
  # GET /shishas
  # GET /shishas.xml
  def index
    @shishas = Shisha.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @shishas }
    end
  end

  # GET /shishas/1
  # GET /shishas/1.xml
  def show
    @shisha = Shisha.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @shisha }
    end
  end

  # GET /shishas/new
  # GET /shishas/new.xml
  def new
    @shisha = Shisha.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @shisha }
    end
  end

  # GET /shishas/1/edit
  def edit
    @shisha = Shisha.find(params[:id])
  end

  # POST /shishas
  # POST /shishas.xml
  def create
    @shisha = Shisha.new(params[:shisha])

    respond_to do |format|
      if @shisha.save
        format.html { redirect_to(@shisha, :notice => 'Shisha was successfully created.') }
        format.xml  { render :xml => @shisha, :status => :created, :location => @shisha }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @shisha.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /shishas/1
  # PUT /shishas/1.xml
  def update
    @shisha = Shisha.find(params[:id])

    respond_to do |format|
      if @shisha.update_attributes(params[:shisha])
        format.html { redirect_to(@shisha, :notice => 'Shisha was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @shisha.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /shishas/1
  # DELETE /shishas/1.xml
  def destroy
    @shisha = Shisha.find(params[:id])
    @shisha.destroy

    respond_to do |format|
      format.html { redirect_to(shishas_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shishas_helper.rb
module ShishasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShishaApp</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shishas/_form.html.erb
<%= form_for(@shisha) do |f| %>
  <% if @shisha.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shisha.errors.count, "error") %> prohibited this shisha from being saved:</h2>

      <ul>
      <% @shisha.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :contact %><br />
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :flavours %><br />
    <%= f.text_area :flavours %>
  </div>
  <div class="field">
    <%= f.label :hours %><br />
    <%= f.text_area :hours %>
  </div>
  <div class="field">
    <%= f.label :facilities %><br />
    <%= f.text_area :facilities %>
  </div>
  <div class="field">
    <%= f.label :image1 %><br />
    <%= f.text_field :image1 %>
  </div>
  <div class="field">
    <%= f.label :image2 %><br />
    <%= f.text_field :image2 %>
  </div>
  <div class="field">
    <%= f.label :image3 %><br />
    <%= f.text_field :image3 %>
  </div>
  <div class="field">
    <%= f.label :image4 %><br />
    <%= f.text_field :image4 %>
  </div>
  <div class="field">
    <%= f.label :isDetailed %><br />
    <%= f.text_field :isDetailed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shishas/edit.html.erb
<h1>Editing shisha</h1>

<%= render 'form' %>

<%= link_to 'Show', @shisha %> |
<%= link_to 'Back', shishas_path %>

app/views/shishas/index.html.erb
<h1>Listing shishas</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Description</th>
    <th>Contact</th>
    <th>Url</th>
    <th>Flavours</th>
    <th>Hours</th>
    <th>Facilities</th>
    <th>Image1</th>
    <th>Image2</th>
    <th>Image3</th>
    <th>Image4</th>
    <th>Isdetailed</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shishas.each do |shisha| %>
  <tr>
    <td><%= shisha.name %></td>
    <td><%= shisha.address %></td>
    <td><%= shisha.latitude %></td>
    <td><%= shisha.longitude %></td>
    <td><%= shisha.description %></td>
    <td><%= shisha.contact %></td>
    <td><%= shisha.url %></td>
    <td><%= shisha.flavours %></td>
    <td><%= shisha.hours %></td>
    <td><%= shisha.facilities %></td>
    <td><%= shisha.image1 %></td>
    <td><%= shisha.image2 %></td>
    <td><%= shisha.image3 %></td>
    <td><%= shisha.image4 %></td>
    <td><%= shisha.isDetailed %></td>
    <td><%= link_to 'Show', shisha %></td>
    <td><%= link_to 'Edit', edit_shisha_path(shisha) %></td>
    <td><%= link_to 'Destroy', shisha, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shisha', new_shisha_path %>

app/views/shishas/new.html.erb
<h1>New shisha</h1>

<%= render 'form' %>

<%= link_to 'Back', shishas_path %>

app/views/shishas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @shisha.name %>
</p>

<p>
  <b>Address:</b>
  <%= @shisha.address %>
</p>

<p>
  <b>Latitude:</b>
  <%= @shisha.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @shisha.longitude %>
</p>

<p>
  <b>Description:</b>
  <%= @shisha.description %>
</p>

<p>
  <b>Contact:</b>
  <%= @shisha.contact %>
</p>

<p>
  <b>Url:</b>
  <%= @shisha.url %>
</p>

<p>
  <b>Flavours:</b>
  <%= @shisha.flavours %>
</p>

<p>
  <b>Hours:</b>
  <%= @shisha.hours %>
</p>

<p>
  <b>Facilities:</b>
  <%= @shisha.facilities %>
</p>

<p>
  <b>Image1:</b>
  <%= @shisha.image1 %>
</p>

<p>
  <b>Image2:</b>
  <%= @shisha.image2 %>
</p>

<p>
  <b>Image3:</b>
  <%= @shisha.image3 %>
</p>

<p>
  <b>Image4:</b>
  <%= @shisha.image4 %>
</p>

<p>
  <b>Isdetailed:</b>
  <%= @shisha.isDetailed %>
</p>


<%= link_to 'Edit', edit_shisha_path(@shisha) %> |
<%= link_to 'Back', shishas_path %>